{
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      },
      adapter: [ 'xhr', 'http' ],
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: { FormData: [Function], Blob: [class Blob] },
      validateStatus: [Function: validateStatus],
      headers: AxiosHeaders {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/pts-m1255v1+json',
        pCHANNEL: 'BACKOFFICE',
        Authorization: 'Bearer eyJhbGciOiJSUzUxMiJ9.eyJwdHlpZCI6IkU4NDA0MTVFMDRFMzE2QUJFMDUzMDEwMDAwN0Y0NDE1IiwiYXVkIjoiT1dOIiwic3ViIjoiRTg0MDQxNUUwNEU0MTZBQkUwNTMwMTAwMDA3RjQ0MTUiLCJjb21wYW5pZXMiOiJbT1dOX0NPTVBBTlldIiwibmJmIjoxNjczNzMxOTUzLCJzY29wZSI6IltcIkZVTExfQVBJX0VYRUNVVE9SX1BUU1wiXSIsImlzcyI6ImFkYXB0b3JPQVMiLCJuYW1lIjoiY2VuY29zdWQiLCJleHAiOjE3MDUyNjgwMTMsImlhdCI6MTY3MzczMjAxMywianRpIjoiN2E3YzEwZDQtOGQ4Yy00ZGE4LWIwOWItY2IxN2JkMmI2MTA3In0.GPPljZJ38k4fFfHtEXmzY6DlW3zQIYWZ0YqCD1IjjhByDNRLGjJwsxu9s9Va1p9a_nOYF4Klo45Hp68VyOa9QDYd66WRvCYzYF_S_7yrAI--RZwxWleGVRHoTAY15VSan2qrQioiyNMp6O-nHmu7zQsHtRTMvukJIrWFUMxGS47T2cdHk7tKDhnTSntulg2WfwUyVNUvqv0s-LE6JCsxlY1j4SSIax8936bo2Fe02_VDXFqJ6Pxhqi2x31oGOGWQI9ZNOAfy-lRBI0y8wXPtwkSu73rn2E9PCs_yLP8VMyEP-agjjNRkK3uPPYtnWpmRqs4Ks6_ZLWT-r6WczPdGew',
        'User-Agent': 'axios/1.3.4',
        'Content-Length': '318',
        'Accept-Encoding': 'gzip, compress, deflate, br'
      },
      method: 'post',
      url: 'https://api-dale-dev.2innovateit.com/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
      data: '{"headerRQ":{"msgId":"PanelAdm449","timestamp":"1678718570"},"securityRQ":{"hostId":"hostname","channelId":"BACKOFFICE"},"messageRQ":{"account":"ABC123","amount":20001,"currency":"COP","transactionChannelId":"123ACB","transactionReason":"nota","type":"CREDITO","importeComision":"1","importeGMF":"1","importeIva":"1"}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype] {
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)],
        finish: [Function: requestOnFinish]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '318',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'api-dale-dev.2innovateit.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'api-dale-dev.2innovateit.com',
        _closeAfterHandlingError: false,
        _readableState: [ReadableState],
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular *1],
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 6068,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: false,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object]
      },
      _header: 'POST /RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/pts-m1255v1+json\r\n' +
        'pCHANNEL: BACKOFFICE\r\n' +
        'Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJwdHlpZCI6IkU4NDA0MTVFMDRFMzE2QUJFMDUzMDEwMDAwN0Y0NDE1IiwiYXVkIjoiT1dOIiwic3ViIjoiRTg0MDQxNUUwNEU0MTZBQkUwNTMwMTAwMDA3RjQ0MTUiLCJjb21wYW5pZXMiOiJbT1dOX0NPTVBBTlldIiwibmJmIjoxNjczNzMxOTUzLCJzY29wZSI6IltcIkZVTExfQVBJX0VYRUNVVE9SX1BUU1wiXSIsImlzcyI6ImFkYXB0b3JPQVMiLCJuYW1lIjoiY2VuY29zdWQiLCJleHAiOjE3MDUyNjgwMTMsImlhdCI6MTY3MzczMjAxMywianRpIjoiN2E3YzEwZDQtOGQ4Yy00ZGE4LWIwOWItY2IxN2JkMmI2MTA3In0.GPPljZJ38k4fFfHtEXmzY6DlW3zQIYWZ0YqCD1IjjhByDNRLGjJwsxu9s9Va1p9a_nOYF4Klo45Hp68VyOa9QDYd66WRvCYzYF_S_7yrAI--RZwxWleGVRHoTAY15VSan2qrQioiyNMp6O-nHmu7zQsHtRTMvukJIrWFUMxGS47T2cdHk7tKDhnTSntulg2WfwUyVNUvqv0s-LE6JCsxlY1j4SSIax8936bo2Fe02_VDXFqJ6Pxhqi2x31oGOGWQI9ZNOAfy-lRBI0y8wXPtwkSu73rn2E9PCs_yLP8VMyEP-agjjNRkK3uPPYtnWpmRqs4Ks6_ZLWT-r6WczPdGew\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Content-Length: 318\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api-dale-dev.2innovateit.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype],
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype],
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: [Object],
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
      _ended: true,
      res: IncomingMessage {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        rawHeaders: [Array],
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular *1],
        responseUrl: 'https://api-dale-dev.2innovateit.com/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
        redirects: [],
        [Symbol(kCapture)]: false,
        [Symbol(kHeaders)]: [Object],
        [Symbol(kHeadersCount)]: 24,
        [Symbol(kTrailers)]: null,
        [Symbol(kTrailersCount)]: 0
      },
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api-dale-dev.2innovateit.com',
      protocol: 'https:',
      _redirectable: Writable {
        _writableState: [WritableState],
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 318,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function (anonymous)],
        _currentRequest: [Circular *1],
        _currentUrl: 'https://api-dale-dev.2innovateit.com/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        pchannel: [Array],
        authorization: [Array],
        'user-agent': [Array],
        'content-length': [Array],
        'accept-encoding': [Array],
        host: [Array]
      },
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: AxiosHeaders {
        date: 'Fri, 24 Mar 2023 17:40:00 GMT',
        'content-type': 'application/pts-m3000v1+json',
        'content-length': '274',
        connection: 'close',
        'cf-cache-status': 'DYNAMIC',
        'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=b%2FaZJTt0%2F7gFNcaRkaNkvzrP%2BH1ohRzxSy4y0FHeGK0TIODHvvHGaHgkucUcXYfwaOijrJY9mg5l%2FHoE043oTUCEcfqJKPIcnu5hPhgN1bsGnkyKdNWlLX%2B4BT8fGoaDHrAXiHj1V8U1p9LaSsnkKBiD1tghdcuUQEE%3D"}],"group":"cf-nel","max_age":604800}',
        nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
        'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        server: 'cloudflare',
        'cf-ray': '7ad0b259ee4e3ef0-BOG',
        'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
      },
      config: {
        transitional: [Object],
        adapter: [Array],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        env: [Object],
        validateStatus: [Function: validateStatus],
        headers: [AxiosHeaders],
        method: 'post',
        url: 'https://api-dale-dev.2innovateit.com/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
        data: '{"headerRQ":{"msgId":"PanelAdm449","timestamp":"1678718570"},"securityRQ":{"hostId":"hostname","channelId":"BACKOFFICE"},"messageRQ":{"account":"ABC123","amount":20001,"currency":"COP","transactionChannelId":"123ACB","transactionReason":"nota","type":"CREDITO","importeComision":"1","importeGMF":"1","importeIva":"1"}}'
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype],
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: '318',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: [TLSSocket],
        _header: 'POST /RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'Content-Type: application/pts-m1255v1+json\r\n' +
          'pCHANNEL: BACKOFFICE\r\n' +
          'Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJwdHlpZCI6IkU4NDA0MTVFMDRFMzE2QUJFMDUzMDEwMDAwN0Y0NDE1IiwiYXVkIjoiT1dOIiwic3ViIjoiRTg0MDQxNUUwNEU0MTZBQkUwNTMwMTAwMDA3RjQ0MTUiLCJjb21wYW5pZXMiOiJbT1dOX0NPTVBBTlldIiwibmJmIjoxNjczNzMxOTUzLCJzY29wZSI6IltcIkZVTExfQVBJX0VYRUNVVE9SX1BUU1wiXSIsImlzcyI6ImFkYXB0b3JPQVMiLCJuYW1lIjoiY2VuY29zdWQiLCJleHAiOjE3MDUyNjgwMTMsImlhdCI6MTY3MzczMjAxMywianRpIjoiN2E3YzEwZDQtOGQ4Yy00ZGE4LWIwOWItY2IxN2JkMmI2MTA3In0.GPPljZJ38k4fFfHtEXmzY6DlW3zQIYWZ0YqCD1IjjhByDNRLGjJwsxu9s9Va1p9a_nOYF4Klo45Hp68VyOa9QDYd66WRvCYzYF_S_7yrAI--RZwxWleGVRHoTAY15VSan2qrQioiyNMp6O-nHmu7zQsHtRTMvukJIrWFUMxGS47T2cdHk7tKDhnTSntulg2WfwUyVNUvqv0s-LE6JCsxlY1j4SSIax8936bo2Fe02_VDXFqJ6Pxhqi2x31oGOGWQI9ZNOAfy-lRBI0y8wXPtwkSu73rn2E9PCs_yLP8VMyEP-agjjNRkK3uPPYtnWpmRqs4Ks6_ZLWT-r6WczPdGew\r\n' +
          'User-Agent: axios/1.3.4\r\n' +
          'Content-Length: 318\r\n' +
          'Accept-Encoding: gzip, compress, deflate, br\r\n' +
          'Host: api-dale-dev.2innovateit.com\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: [Agent],
        socketPath: undefined,
        method: 'POST',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/RSAdaptorFE/api/v2/own-channels/custom/service/PANEL_ADMINISTRATIVO/execute',
        _ended: true,
        res: [IncomingMessage],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'api-dale-dev.2innovateit.com',
        protocol: 'https:',
        _redirectable: [Writable],
        [Symbol(kCapture)]: false,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(kEndCalled)]: true,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype],
        [Symbol(kUniqueHeaders)]: null
      },
      data: { messageRS: [Object], headerRS: [Object], statusRS: [Object] }
    }
  }